spring:
  application:
    name: authorization-features
  jpa:
    open-in-view: false
    show-sql: true
  datasource:
    url: jdbc:h2:mem:authorization-features

logging:
  level:
    org.springframework.security: debug
    org.hibernate.orm.jdbc.bind: trace

server:
  error:
    include-stacktrace: never