spring:
  application:
    name: target-resource-server
  security:
    oauth2:
      resourceserver:
        jwt:
          audiences: http://localhost:9092/api/messages
          jwk-set-uri: http://localhost:9000/oauth2/jwks

server:
  port: 9092

logging:
  level:
    org.springframework.security: trace