spring:
  application:
    name:
      security-filter-chain-validation
logging:
  level:
    org.springframework.security: debug
management:
  endpoints:
    web:
      exposure:
        include: '*'